backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  branch: main  # 또는 master, 현재 쓰고 있는 기본 브랜치 이름

media_folder: "public/images/uploads"   # 업로드 파일 저장 경로
public_folder: "/images/uploads"        # 웹에서 접근하는 경로

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

